---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: python
        types: [python]
        args: [--skip-string-normalization]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        types: [python]
        args: [--max-line-length=88]

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        types: [python]

      - id: shellcheck
        name: shellcheck
        entry: poetry run shellcheck
        language: system
        types: [shell]
